"""Prompt 模板模块"""

from src.llm.prompts.system_prompts import (
    PERFORMANCE_EXPERT_SYSTEM,
    TIMELINE_ANALYSIS_SYSTEM,
    MFU_ANALYSIS_SYSTEM,
    SLOW_RANK_ANALYSIS_SYSTEM,
    COMMUNICATION_ANALYSIS_SYSTEM,
    ADVISOR_SYSTEM,
)

__all__ = [
    "PERFORMANCE_EXPERT_SYSTEM",
    "TIMELINE_ANALYSIS_SYSTEM",
    "MFU_ANALYSIS_SYSTEM",
    "SLOW_RANK_ANALYSIS_SYSTEM",
    "COMMUNICATION_ANALYSIS_SYSTEM",
    "ADVISOR_SYSTEM",
]
